/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type AccentText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal";
  listItem?: never;
  markDefs?: null;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type TrialResultReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "trialResult";
};

export type TrialResultList = {
  _type: "trialResultList";
  cases: Array<
    {
      _key: string;
    } & TrialResultReference
  >;
};

export type EducationEntry = {
  _type: "educationEntry";
  school: string;
  location?: string;
  lines: Array<string>;
};

export type ConsultContent = {
  _type: "consultContent";
  eyebrow: string;
  headingLead: string;
  headingStrong: string;
  body: BlockContent;
  fineprint: string;
  thankYou: string;
};

export type CtaBarContent = {
  _type: "ctaBarContent";
  eyebrow: string;
  headingLead: string;
  headingRest: string;
  body: BlockContent;
  cta: CtaButton;
};

export type NewsItemReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "newsItem";
};

export type NewsBand = {
  _type: "newsBand";
  eyebrow: string;
  headingLead: string;
  headingStrong: string;
  lede: BlockContent;
  featured: NewsItemReference;
};

export type FaqReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "faq";
};

export type FaqBand = {
  _type: "faqBand";
  eyebrow: string;
  headingLead: string;
  headingStrong: string;
  lede: BlockContent;
  questions: Array<
    {
      _key: string;
    } & FaqReference
  >;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type PressLogo = {
  _type: "pressLogo";
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt: string;
};

export type PracticeReachStat = {
  _type: "practiceReachStat";
  label: string;
  value: string;
};

export type WhyChooseBand = {
  _type: "whyChooseBand";
  eyebrow: string;
  headingLead: string;
  headingStrong: string;
  features: Array<
    {
      _key: string;
    } & WhyChooseFeature
  >;
};

export type WhyChooseFeature = {
  _type: "whyChooseFeature";
  title: string;
  body: string;
  icon: "trophy" | "landmark" | "check" | "shield";
};

export type TestimonialsWallBand = {
  _type: "testimonialsWallBand";
  eyebrow: string;
  headingLead: string;
  headingStrong: string;
  lede: BlockContent;
};

export type TestimonialsBand = {
  _type: "testimonialsBand";
  eyebrow: string;
  headingLead: string;
  headingStrong: string;
};

export type AttorneysBand = {
  _type: "attorneysBand";
  eyebrow: string;
  headingLead: string;
  headingStrong: string;
  lede: BlockContent;
};

export type PracticeAreasBand = {
  _type: "practiceAreasBand";
  eyebrow: string;
  headingLead: string;
  headingStrong: string;
  description: BlockContent;
  cards: Array<
    {
      _key: string;
    } & PracticeAreaCard
  >;
};

export type PracticeAreaCard = {
  _type: "practiceAreaCard";
  title: string;
  desc: string;
  icon: "briefcase" | "users" | "layers" | "columns" | "search" | "doc";
};

export type SellingPoint = {
  _type: "sellingPoint";
  value: string;
  label: string;
};

export type CtaButton = {
  _type: "ctaButton";
  label: string;
  href: string;
};

export type ServiceCityReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "serviceCity";
};

export type LocationPage = {
  _id: string;
  _type: "locationPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  city: ServiceCityReference;
  title: string;
  navLabel: string;
  slug: Slug;
  heroTitle: string;
  lede?: string;
  intro?: BlockContent;
  sections?: Array<{
    heading: string;
    body: BlockContent;
    _type: "section";
    _key: string;
  }>;
  faqs?: Array<{
    question: string;
    answer: BlockContent;
    _type: "practiceFaq";
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type ServiceCity = {
  _id: string;
  _type: "serviceCity";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  city: string;
  citySlug: Slug;
};

export type PracticeAreaReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "practiceArea";
};

export type PracticeArea = {
  _id: string;
  _type: "practiceArea";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title: string;
  slug: Slug;
  parent?: PracticeAreaReference;
  heroTitle: string;
  lede?: string;
  cardSummary?: string;
  icon?: "health" | "federal" | "fraud" | "collar" | "appeals";
  intro?: BlockContent;
  sections?: Array<{
    heading: string;
    body: BlockContent;
    _type: "section";
    _key: string;
  }>;
  faqs?: Array<{
    question: string;
    answer: BlockContent;
    _type: "practiceFaq";
    _key: string;
  }>;
};

export type LegalPage = {
  _id: string;
  _type: "legalPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  intro: BlockContent;
  sections?: Array<{
    heading: string;
    body: BlockContent;
    _type: "section";
    _key: string;
  }>;
};

export type NewsItem = {
  _id: string;
  _type: "newsItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  outlet: string;
  outletLogo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  media: "article" | "video" | "podcast";
  summary: string;
  publishedAt?: string;
  linkType: "external" | "article";
  externalUrl?: string;
  ctaLabel?: string;
  body?: BlockContent;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  question: string;
  answer: BlockContent;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  quote: string;
  author: string;
  tag?: string;
  featured?: boolean;
};

export type Attorney = {
  _id: string;
  _type: "attorney";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  name: string;
  slug: Slug;
  role: string;
  credential: string;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  photoAlt: string;
  phone: string;
  email?: string;
  practiceTags: Array<string>;
  bio?: BlockContent;
  education: Array<
    {
      _key: string;
    } & EducationEntry
  >;
  barAdmissions: Array<string>;
  honors: Array<string>;
  classesSeminars?: Array<string>;
  publishedWorks?: Array<string>;
  associations?: Array<string>;
  pastPositions?: Array<string>;
  representativeCases?: Array<string>;
  consult?: ConsultContent;
};

export type TrialResult = {
  _id: string;
  _type: "trialResult";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  outcome: string;
  note: string;
  category: "landmark" | "federal" | "fraud";
  categoryLabel:
    | "Landmark Case"
    | "Federal Victory"
    | "White Collar"
    | "Health Care Fraud"
    | "Federal Fraud";
  teaser?: {
    title?: string;
    outcome?: string;
    note?: string;
  };
};

export type Consult = {
  _id: string;
  _type: "consult";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  content: ConsultContent;
};

export type CtaBar = {
  _id: string;
  _type: "ctaBar";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  content: CtaBarContent;
};

export type PracticeAreasPage = {
  _id: string;
  _type: "practiceAreasPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  consult?: ConsultContent;
};

export type NewsPage = {
  _id: string;
  _type: "newsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  grid?: {
    eyebrow: string;
    headingLead: string;
    headingStrong: string;
  };
  consult?: ConsultContent;
};

export type VideosPage = {
  _id: string;
  _type: "videosPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  grid?: {
    eyebrow: string;
    headingLead: string;
    headingStrong: string;
  };
  consult?: ConsultContent;
};

export type OurFirmPage = {
  _id: string;
  _type: "ourFirmPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  consult?: ConsultContent;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  consult?: ConsultContent;
};

export type AttorneysPage = {
  _id: string;
  _type: "attorneysPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  attorneys?: AttorneysBand;
  testimonials?: TestimonialsBand;
  whyChoose?: WhyChooseBand;
  consult?: ConsultContent;
};

export type TestimonialsPage = {
  _id: string;
  _type: "testimonialsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  testimonialsWall?: TestimonialsWallBand;
  practiceAreas?: PracticeAreasBand;
  ctaBar?: CtaBarContent;
  consult?: ConsultContent;
};

export type TrialExperiencePage = {
  _id: string;
  _type: "trialExperiencePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  trialResults?: TrialResultList;
  practiceAreas?: PracticeAreasBand;
  ctaBar?: CtaBarContent;
  consult?: ConsultContent;
};

export type VideoReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "video";
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    eyebrow: string;
    titleAccent: string;
    titleSecond: string;
    lead: BlockContent;
    ctas?: Array<
      {
        _key: string;
      } & CtaButton
    >;
    caption?: {
      name: string;
      role: string;
      watchLabel: string;
      video: VideoReference;
    };
  };
  sellingPoints?: {
    points: Array<
      {
        _key: string;
      } & SellingPoint
    >;
  };
  practiceAreas?: PracticeAreasBand;
  about?: {
    eyebrow: string;
    titleLead: string;
    titleStrong: string;
    body: BlockContent;
    resultsEyebrow: string;
    featured: Array<
      {
        _key: string;
      } & TrialResultReference
    >;
    quote: AccentText;
  };
  statement?: {
    eyebrow: string;
    headingItalic: string;
    headingBold: string;
    body: BlockContent;
    cta: CtaButton;
  };
  ctaBar?: CtaBarContent;
  attorneys?: AttorneysBand;
  firmStory?: {
    eyebrow: string;
    headingLead: string;
    headingStrong: string;
    body: BlockContent;
    cta: CtaButton;
  };
  testimonials?: TestimonialsBand;
  whyChoose?: WhyChooseBand;
  practiceReach?: {
    eyebrow: string;
    headingLead: string;
    headingStrong: string;
    lede: BlockContent;
    stats: Array<
      {
        _key: string;
      } & PracticeReachStat
    >;
  };
  press?: {
    logos: Array<
      {
        _key: string;
      } & PressLogo
    >;
  };
  faq?: FaqBand;
  news?: NewsBand;
  consult?: ConsultContent;
};

export type Video = {
  _id: string;
  _type: "video";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title: string;
  wistiaId: string;
};

export type FirmDetails = {
  _id: string;
  _type: "firmDetails";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  tagline: string;
  phone: string;
  email: string;
  address?: {
    street: string;
    cityStateZip: string;
  };
  socials?: Array<{
    platform: "facebook" | "x" | "linkedin" | "instagram" | "youtube";
    url: string;
    _type: "social";
    _key: string;
  }>;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  copyrightNotice: string;
  legalLinks?: Array<{
    label: string;
    href: string;
    _type: "legalLink";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | AccentText
  | BlockContent
  | TrialResultReference
  | TrialResultList
  | EducationEntry
  | ConsultContent
  | CtaBarContent
  | NewsItemReference
  | NewsBand
  | FaqReference
  | FaqBand
  | SanityImageAssetReference
  | PressLogo
  | PracticeReachStat
  | WhyChooseBand
  | WhyChooseFeature
  | TestimonialsWallBand
  | TestimonialsBand
  | AttorneysBand
  | PracticeAreasBand
  | PracticeAreaCard
  | SellingPoint
  | CtaButton
  | ServiceCityReference
  | LocationPage
  | Slug
  | ServiceCity
  | PracticeAreaReference
  | PracticeArea
  | LegalPage
  | NewsItem
  | SanityImageCrop
  | SanityImageHotspot
  | Faq
  | Testimonial
  | Attorney
  | TrialResult
  | Consult
  | CtaBar
  | PracticeAreasPage
  | NewsPage
  | VideosPage
  | OurFirmPage
  | ContactPage
  | AttorneysPage
  | TestimonialsPage
  | TrialExperiencePage
  | VideoReference
  | HomePage
  | Video
  | FirmDetails
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/areasWeServe.ts
// Variable: PATHS_QUERY
// Query: *[_type == "locationPage"] | order(orderRank){  _id,  title,  navLabel,  heroTitle,  lede,  intro,  sections[]{ _key, heading, body },  faqs[]{ _key, question, answer },  "slug": slug.current,  "cityName": city->city,  "citySlug": city->citySlug.current}
export type PATHS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  navLabel: string;
  heroTitle: string;
  lede: string | null;
  intro: BlockContent | null;
  sections: Array<{
    _key: string;
    heading: string;
    body: BlockContent;
  }> | null;
  faqs: Array<{
    _key: string;
    question: string;
    answer: BlockContent;
  }> | null;
  slug: string;
  cityName: string;
  citySlug: string;
}>;

// Source: src/sanity/lib/attorneys.ts
// Variable: ATTORNEY_CARDS_QUERY
// Query: *[_type == "attorney"] | order(orderRank){  _id,  name,  role,  credential,  photo,  photoAlt,  "slug": slug.current}
export type ATTORNEY_CARDS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  role: string;
  credential: string;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  photoAlt: string;
  slug: string;
}>;

// Source: src/sanity/lib/attorneys.ts
// Variable: ATTORNEY_SLUGS_QUERY
// Query: *[_type == "attorney" && defined(slug.current)]{"slug": slug.current}
export type ATTORNEY_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: src/sanity/lib/attorneys.ts
// Variable: ATTORNEY_QUERY
// Query: *[_type == "attorney" && slug.current == $slug][0]{  _id,  name,  role,  credential,  photo,  photoAlt,  phone,  email,  practiceTags,  bio,  education[]{    _key,    school,    location,    lines  },  barAdmissions,  honors,  classesSeminars,  publishedWorks,  associations,  pastPositions,  representativeCases,  "slug": slug.current}
export type ATTORNEY_QUERY_RESULT = {
  _id: string;
  name: string;
  role: string;
  credential: string;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  photoAlt: string;
  phone: string;
  email: string | null;
  practiceTags: Array<string>;
  bio: BlockContent | null;
  education: Array<{
    _key: string;
    school: string;
    location: string | null;
    lines: Array<string>;
  }>;
  barAdmissions: Array<string>;
  honors: Array<string>;
  classesSeminars: Array<string> | null;
  publishedWorks: Array<string> | null;
  associations: Array<string> | null;
  pastPositions: Array<string> | null;
  representativeCases: Array<string> | null;
  slug: string;
} | null;

// Source: src/sanity/lib/attorneys.ts
// Variable: ATTORNEYS_BAND_QUERY
// Query: *[_id == $pageId][0].attorneys{  eyebrow,  headingLead,  headingStrong,  lede}
export type ATTORNEYS_BAND_QUERY_RESULT = {
  eyebrow: string;
  headingLead: string;
  headingStrong: string;
  lede: BlockContent;
} | null;

// Source: src/sanity/lib/consult.ts
// Variable: CONSULT_QUERY
// Query: coalesce(  *[_id == $pageId][0].consult,  *[_id == "consult"][0].content){  eyebrow,  headingLead,  headingStrong,  body,  fineprint,  thankYou}
export type CONSULT_QUERY_RESULT =
  | {
      eyebrow: string;
      headingLead: string;
      headingStrong: null;
      body: BlockContent;
      fineprint: null;
      thankYou: null;
    }
  | {
      eyebrow: string;
      headingLead: string;
      headingStrong: string;
      body: BlockContent;
      fineprint: string;
      thankYou: string;
    }
  | null;

// Source: src/sanity/lib/ctaBar.ts
// Variable: CTA_BAR_QUERY
// Query: coalesce(  *[_id == $pageId][0].ctaBar,  *[_id == "ctaBar"][0].content){  eyebrow,  headingLead,  headingRest,  body,  cta{    label,    href  }}
export type CTA_BAR_QUERY_RESULT =
  | {
      eyebrow: string;
      headingLead: string;
      headingRest: null;
      body: BlockContent;
      cta: null;
    }
  | {
      eyebrow: string;
      headingLead: string;
      headingRest: string;
      body: BlockContent;
      cta: {
        label: string;
        href: string;
      };
    }
  | null;

// Source: src/sanity/lib/faqs.ts
// Variable: FAQS_QUERY
// Query: *[_type == "faq"] | order(orderRank){  _id,  question,  answer}
export type FAQS_QUERY_RESULT = Array<{
  _id: string;
  question: string;
  answer: BlockContent;
}>;

// Source: src/sanity/lib/faqs.ts
// Variable: FAQ_BAND_QUERY
// Query: *[_id == "homePage"][0].faq{  eyebrow,  headingLead,  headingStrong,  lede,  questions[]->{    _id,    question,    answer  }}
export type FAQ_BAND_QUERY_RESULT = {
  eyebrow: string;
  headingLead: string;
  headingStrong: string;
  lede: BlockContent;
  questions: Array<{
    _id: string;
    question: string;
    answer: BlockContent;
  }>;
} | null;

// Source: src/sanity/lib/firmDetails.ts
// Variable: FIRM_DETAILS_QUERY
// Query: *[_id == "firmDetails"][0]{  title,  tagline,  phone,  email,  address,  socials[]{    platform,    url  },  copyrightNotice,  legalLinks[]{    label,    href  },  logo{    ...,    "dimensions": asset->metadata.dimensions  }}
export type FIRM_DETAILS_QUERY_RESULT =
  | {
      title: null;
      tagline: null;
      phone: null;
      email: null;
      address: null;
      socials: null;
      copyrightNotice: null;
      legalLinks: null;
      logo: null;
    }
  | {
      title: string;
      tagline: null;
      phone: null;
      email: null;
      address: null;
      socials: null;
      copyrightNotice: null;
      legalLinks: null;
      logo: null;
    }
  | {
      title: string | null;
      tagline: null;
      phone: null;
      email: null;
      address: null;
      socials: null;
      copyrightNotice: null;
      legalLinks: null;
      logo: null;
    }
  | {
      title: null;
      tagline: null;
      phone: string;
      email: string | null;
      address: null;
      socials: null;
      copyrightNotice: null;
      legalLinks: null;
      logo: null;
    }
  | {
      title: string;
      tagline: string;
      phone: string;
      email: string;
      address: {
        street: string;
        cityStateZip: string;
      } | null;
      socials: Array<{
        platform: "facebook" | "instagram" | "linkedin" | "x" | "youtube";
        url: string;
      }> | null;
      copyrightNotice: string;
      legalLinks: Array<{
        label: string;
        href: string;
      }> | null;
      logo: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        dimensions: SanityImageDimensions | null;
      } | null;
    }
  | null;

// Source: src/sanity/lib/homePage.ts
// Variable: HOME_HERO_QUERY
// Query: *[_id == "homePage"][0].hero{  eyebrow,  titleAccent,  titleSecond,  lead,  ctas[]{    _key,    label,    href  },  caption{    name,    role,    watchLabel,    video->{      wistiaId    }  }}
export type HOME_HERO_QUERY_RESULT = null | {
  eyebrow: string;
  titleAccent: string;
  titleSecond: string;
  lead: BlockContent;
  ctas: Array<{
    _key: string;
    label: string;
    href: string;
  }> | null;
  caption: {
    name: string;
    role: string;
    watchLabel: string;
    video: {
      wistiaId: string;
    };
  } | null;
};

// Source: src/sanity/lib/homePage.ts
// Variable: HOME_SELLING_POINTS_QUERY
// Query: *[_id == "homePage"][0].sellingPoints.points[]{  _key,  value,  label}
export type HOME_SELLING_POINTS_QUERY_RESULT = Array<{
  _key: string;
  value: string;
  label: string;
}> | null;

// Source: src/sanity/lib/homePage.ts
// Variable: HOME_ABOUT_QUERY
// Query: *[_id == "homePage"][0].about{  eyebrow,  titleLead,  titleStrong,  body,  resultsEyebrow,  quote,  featured[]->{    _id,    "outcome": coalesce(teaser.outcome, outcome),    "caseName": coalesce(teaser.title, name),    "note": coalesce(teaser.note, note)  }}
export type HOME_ABOUT_QUERY_RESULT = null | {
  eyebrow: string;
  titleLead: string;
  titleStrong: string;
  body: BlockContent;
  resultsEyebrow: string;
  quote: AccentText;
  featured: Array<{
    _id: string;
    outcome: string;
    caseName: string;
    note: string;
  }>;
};

// Source: src/sanity/lib/homePage.ts
// Variable: HOME_STATEMENT_QUERY
// Query: *[_id == "homePage"][0].statement{  eyebrow,  headingItalic,  headingBold,  body,  cta{    label,    href  }}
export type HOME_STATEMENT_QUERY_RESULT = null | {
  eyebrow: string;
  headingItalic: string;
  headingBold: string;
  body: BlockContent;
  cta: {
    label: string;
    href: string;
  };
};

// Source: src/sanity/lib/homePage.ts
// Variable: HOME_FIRM_STORY_QUERY
// Query: *[_id == "homePage"][0].firmStory{  eyebrow,  headingLead,  headingStrong,  body,  cta{    label,    href  }}
export type HOME_FIRM_STORY_QUERY_RESULT = null | {
  eyebrow: string;
  headingLead: string;
  headingStrong: string;
  body: BlockContent;
  cta: {
    label: string;
    href: string;
  };
};

// Source: src/sanity/lib/homePage.ts
// Variable: HOME_PRACTICE_REACH_QUERY
// Query: *[_id == "homePage"][0].practiceReach{  eyebrow,  headingLead,  headingStrong,  lede,  stats[]{    _key,    label,    value  }}
export type HOME_PRACTICE_REACH_QUERY_RESULT = null | {
  eyebrow: string;
  headingLead: string;
  headingStrong: string;
  lede: BlockContent;
  stats: Array<{
    _key: string;
    label: string;
    value: string;
  }>;
};

// Source: src/sanity/lib/homePage.ts
// Variable: HOME_PRESS_QUERY
// Query: *[_id == "homePage"][0].press.logos[]{  _key,  alt,  image,  "dimensions": image.asset->metadata.dimensions}
export type HOME_PRESS_QUERY_RESULT = Array<{
  _key: string;
  alt: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  dimensions: SanityImageDimensions | null;
}> | null;

// Source: src/sanity/lib/legalPages.ts
// Variable: LEGAL_PAGE_QUERY
// Query: *[_id == $id][0]{  title,  intro,  sections[]{    _key,    heading,    body  }}
export type LEGAL_PAGE_QUERY_RESULT =
  | {
      title: string;
      intro: BlockContent;
      sections: Array<{
        _key: string;
        heading: string;
        body: BlockContent;
      }> | null;
    }
  | {
      title: null;
      intro: null;
      sections: null;
    }
  | {
      title: string;
      intro: null;
      sections: null;
    }
  | {
      title: string | null;
      intro: null;
      sections: null;
    }
  | {
      title: string;
      intro: BlockContent | null;
      sections: Array<{
        _key: string;
        heading: string;
        body: BlockContent;
      }> | null;
    }
  | null;

// Source: src/sanity/lib/news.ts
// Variable: ALL_NEWS_QUERY
// Query: *[_type == "newsItem"] | order(coalesce(publishedAt, _createdAt) desc){  _id,  title,  outlet,  media,  summary,  ctaLabel,  linkType,  externalUrl,  "slug": slug.current,  "date": coalesce(publishedAt, _createdAt),  outletLogo}
export type ALL_NEWS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  outlet: string;
  media: "article" | "podcast" | "video";
  summary: string;
  ctaLabel: string | null;
  linkType: "article" | "external";
  externalUrl: string | null;
  slug: string;
  date: string;
  outletLogo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/lib/news.ts
// Variable: NEWS_BAND_QUERY
// Query: *[_id == "homePage"][0].news{  eyebrow,  headingLead,  headingStrong,  lede,  "featured": featured->{  _id,  title,  outlet,  media,  summary,  ctaLabel,  linkType,  externalUrl,  "slug": slug.current,  "date": coalesce(publishedAt, _createdAt),  outletLogo},  "featuredId": featured._ref}
export type NEWS_BAND_QUERY_RESULT = {
  eyebrow: string;
  headingLead: string;
  headingStrong: string;
  lede: BlockContent;
  featured: {
    _id: string;
    title: string;
    outlet: string;
    media: "article" | "podcast" | "video";
    summary: string;
    ctaLabel: string | null;
    linkType: "article" | "external";
    externalUrl: string | null;
    slug: string;
    date: string;
    outletLogo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  };
  featuredId: string;
} | null;

// Source: src/sanity/lib/news.ts
// Variable: NEWS_ITEM_QUERY
// Query: *[_type == "newsItem" && slug.current == $slug][0]{  _id,  title,  outlet,  summary,  body,  "slug": slug.current}
export type NEWS_ITEM_QUERY_RESULT = {
  _id: string;
  title: string;
  outlet: string;
  summary: string;
  body: BlockContent | null;
  slug: string;
} | null;

// Source: src/sanity/lib/news.ts
// Variable: OWNED_NEWS_SLUGS_QUERY
// Query: *[_type == "newsItem" && linkType == "article" && defined(slug.current)]{"slug": slug.current}
export type OWNED_NEWS_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: src/sanity/lib/news.ts
// Variable: NEWS_GRID_HEADER_QUERY
// Query: *[_id == "newsPage"][0].grid{  eyebrow,  headingLead,  headingStrong}
export type NEWS_GRID_HEADER_QUERY_RESULT = null | {
  eyebrow: string;
  headingLead: string;
  headingStrong: string;
};

// Source: src/sanity/lib/practiceAreas.ts
// Variable: ALL_QUERY
// Query: *[_type == "practiceArea"] | order(orderRank){  _id,  title,  heroTitle,  lede,  cardSummary,  icon,  intro,  sections[]{ _key, heading, body },  faqs[]{ _key, question, answer },  "slug": slug.current,  "parentId": parent._ref}
export type ALL_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  heroTitle: string;
  lede: string | null;
  cardSummary: string | null;
  icon: "appeals" | "collar" | "federal" | "fraud" | "health" | null;
  intro: BlockContent | null;
  sections: Array<{
    _key: string;
    heading: string;
    body: BlockContent;
  }> | null;
  faqs: Array<{
    _key: string;
    question: string;
    answer: BlockContent;
  }> | null;
  slug: string;
  parentId: string | null;
}>;

// Source: src/sanity/lib/practiceAreasBand.ts
// Variable: PRACTICE_AREAS_BAND_QUERY
// Query: *[_id == $pageId][0].practiceAreas{  eyebrow,  headingLead,  headingStrong,  description,  cards[]{    _key,    icon,    title,    desc  }}
export type PRACTICE_AREAS_BAND_QUERY_RESULT = {
  eyebrow: string;
  headingLead: string;
  headingStrong: string;
  description: BlockContent;
  cards: Array<{
    _key: string;
    icon: "briefcase" | "columns" | "doc" | "layers" | "search" | "users";
    title: string;
    desc: string;
  }>;
} | null;

// Source: src/sanity/lib/testimonials.ts
// Variable: FEATURED_TESTIMONIALS_QUERY
// Query: *[  _type == "testimonial" && featured == true] | order(orderRank) [0...3]{  _id,  quote,  author,  tag}
export type FEATURED_TESTIMONIALS_QUERY_RESULT = Array<{
  _id: string;
  quote: string;
  author: string;
  tag: string | null;
}>;

// Source: src/sanity/lib/testimonials.ts
// Variable: ALL_TESTIMONIALS_QUERY
// Query: *[_type == "testimonial"] | order(orderRank){  _id,  quote,  author}
export type ALL_TESTIMONIALS_QUERY_RESULT = Array<{
  _id: string;
  quote: string;
  author: string;
}>;

// Source: src/sanity/lib/testimonials.ts
// Variable: TESTIMONIALS_BAND_QUERY
// Query: *[_id == $pageId][0].testimonials{  eyebrow,  headingLead,  headingStrong}
export type TESTIMONIALS_BAND_QUERY_RESULT = {
  eyebrow: string;
  headingLead: string;
  headingStrong: string;
} | null;

// Source: src/sanity/lib/testimonials.ts
// Variable: TESTIMONIALS_WALL_BAND_QUERY
// Query: *[_id == "testimonialsPage"][0].testimonialsWall{  eyebrow,  headingLead,  headingStrong,  lede}
export type TESTIMONIALS_WALL_BAND_QUERY_RESULT = {
  eyebrow: string;
  headingLead: string;
  headingStrong: string;
  lede: BlockContent;
} | null;

// Source: src/sanity/lib/trialResults.ts
// Variable: TRIAL_RESULTS_QUERY
// Query: *[_id == "trialExperiencePage"][0].trialResults.cases[]->{  _id,  name,  outcome,  note,  category,  categoryLabel}
export type TRIAL_RESULTS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  outcome: string;
  note: string;
  category: "federal" | "fraud" | "landmark";
  categoryLabel:
    | "Federal Fraud"
    | "Federal Victory"
    | "Health Care Fraud"
    | "Landmark Case"
    | "White Collar";
}> | null;

// Source: src/sanity/lib/videos.ts
// Variable: VIDEOS_QUERY
// Query: *[_type == "video"] | order(orderRank){  _id,  title,  wistiaId}
export type VIDEOS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  wistiaId: string;
}>;

// Source: src/sanity/lib/videos.ts
// Variable: VIDEO_GRID_HEADER_QUERY
// Query: *[_id == "videosPage"][0].grid{  eyebrow,  headingLead,  headingStrong}
export type VIDEO_GRID_HEADER_QUERY_RESULT = null | {
  eyebrow: string;
  headingLead: string;
  headingStrong: string;
};

// Source: src/sanity/lib/whyChoose.ts
// Variable: WHY_CHOOSE_BAND_QUERY
// Query: *[_id == $pageId][0].whyChoose{  eyebrow,  headingLead,  headingStrong,  features[]{    _key,    icon,    title,    body  }}
export type WHY_CHOOSE_BAND_QUERY_RESULT = {
  eyebrow: string;
  headingLead: string;
  headingStrong: string;
  features: Array<{
    _key: string;
    icon: "check" | "landmark" | "shield" | "trophy";
    title: string;
    body: string;
  }>;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "locationPage"] | order(orderRank){\n  _id,\n  title,\n  navLabel,\n  heroTitle,\n  lede,\n  intro,\n  sections[]{ _key, heading, body },\n  faqs[]{ _key, question, answer },\n  "slug": slug.current,\n  "cityName": city->city,\n  "citySlug": city->citySlug.current\n}': PATHS_QUERY_RESULT;
    '*[_type == "attorney"] | order(orderRank){\n  _id,\n  name,\n  role,\n  credential,\n  photo,\n  photoAlt,\n  "slug": slug.current\n}': ATTORNEY_CARDS_QUERY_RESULT;
    '*[_type == "attorney" && defined(slug.current)]{"slug": slug.current}': ATTORNEY_SLUGS_QUERY_RESULT;
    '*[_type == "attorney" && slug.current == $slug][0]{\n  _id,\n  name,\n  role,\n  credential,\n  photo,\n  photoAlt,\n  phone,\n  email,\n  practiceTags,\n  bio,\n  education[]{\n    _key,\n    school,\n    location,\n    lines\n  },\n  barAdmissions,\n  honors,\n  classesSeminars,\n  publishedWorks,\n  associations,\n  pastPositions,\n  representativeCases,\n  "slug": slug.current\n}': ATTORNEY_QUERY_RESULT;
    "*[_id == $pageId][0].attorneys{\n  eyebrow,\n  headingLead,\n  headingStrong,\n  lede\n}": ATTORNEYS_BAND_QUERY_RESULT;
    'coalesce(\n  *[_id == $pageId][0].consult,\n  *[_id == "consult"][0].content\n){\n  eyebrow,\n  headingLead,\n  headingStrong,\n  body,\n  fineprint,\n  thankYou\n}': CONSULT_QUERY_RESULT;
    'coalesce(\n  *[_id == $pageId][0].ctaBar,\n  *[_id == "ctaBar"][0].content\n){\n  eyebrow,\n  headingLead,\n  headingRest,\n  body,\n  cta{\n    label,\n    href\n  }\n}': CTA_BAR_QUERY_RESULT;
    '*[_type == "faq"] | order(orderRank){\n  _id,\n  question,\n  answer\n}': FAQS_QUERY_RESULT;
    '*[_id == "homePage"][0].faq{\n  eyebrow,\n  headingLead,\n  headingStrong,\n  lede,\n  questions[]->{\n    _id,\n    question,\n    answer\n  }\n}': FAQ_BAND_QUERY_RESULT;
    '*[_id == "firmDetails"][0]{\n  title,\n  tagline,\n  phone,\n  email,\n  address,\n  socials[]{\n    platform,\n    url\n  },\n  copyrightNotice,\n  legalLinks[]{\n    label,\n    href\n  },\n  logo{\n    ...,\n    "dimensions": asset->metadata.dimensions\n  }\n}': FIRM_DETAILS_QUERY_RESULT;
    '*[_id == "homePage"][0].hero{\n  eyebrow,\n  titleAccent,\n  titleSecond,\n  lead,\n  ctas[]{\n    _key,\n    label,\n    href\n  },\n  caption{\n    name,\n    role,\n    watchLabel,\n    video->{\n      wistiaId\n    }\n  }\n}': HOME_HERO_QUERY_RESULT;
    '*[_id == "homePage"][0].sellingPoints.points[]{\n  _key,\n  value,\n  label\n}': HOME_SELLING_POINTS_QUERY_RESULT;
    '*[_id == "homePage"][0].about{\n  eyebrow,\n  titleLead,\n  titleStrong,\n  body,\n  resultsEyebrow,\n  quote,\n  featured[]->{\n    _id,\n    "outcome": coalesce(teaser.outcome, outcome),\n    "caseName": coalesce(teaser.title, name),\n    "note": coalesce(teaser.note, note)\n  }\n}': HOME_ABOUT_QUERY_RESULT;
    '*[_id == "homePage"][0].statement{\n  eyebrow,\n  headingItalic,\n  headingBold,\n  body,\n  cta{\n    label,\n    href\n  }\n}': HOME_STATEMENT_QUERY_RESULT;
    '*[_id == "homePage"][0].firmStory{\n  eyebrow,\n  headingLead,\n  headingStrong,\n  body,\n  cta{\n    label,\n    href\n  }\n}': HOME_FIRM_STORY_QUERY_RESULT;
    '*[_id == "homePage"][0].practiceReach{\n  eyebrow,\n  headingLead,\n  headingStrong,\n  lede,\n  stats[]{\n    _key,\n    label,\n    value\n  }\n}': HOME_PRACTICE_REACH_QUERY_RESULT;
    '*[_id == "homePage"][0].press.logos[]{\n  _key,\n  alt,\n  image,\n  "dimensions": image.asset->metadata.dimensions\n}': HOME_PRESS_QUERY_RESULT;
    "*[_id == $id][0]{\n  title,\n  intro,\n  sections[]{\n    _key,\n    heading,\n    body\n  }\n}": LEGAL_PAGE_QUERY_RESULT;
    '*[_type == "newsItem"] | order(coalesce(publishedAt, _createdAt) desc){\n  _id,\n  title,\n  outlet,\n  media,\n  summary,\n  ctaLabel,\n  linkType,\n  externalUrl,\n  "slug": slug.current,\n  "date": coalesce(publishedAt, _createdAt),\n  outletLogo\n}': ALL_NEWS_QUERY_RESULT;
    '*[_id == "homePage"][0].news{\n  eyebrow,\n  headingLead,\n  headingStrong,\n  lede,\n  "featured": featured->{\n  _id,\n  title,\n  outlet,\n  media,\n  summary,\n  ctaLabel,\n  linkType,\n  externalUrl,\n  "slug": slug.current,\n  "date": coalesce(publishedAt, _createdAt),\n  outletLogo\n},\n  "featuredId": featured._ref\n}': NEWS_BAND_QUERY_RESULT;
    '*[_type == "newsItem" && slug.current == $slug][0]{\n  _id,\n  title,\n  outlet,\n  summary,\n  body,\n  "slug": slug.current\n}': NEWS_ITEM_QUERY_RESULT;
    '*[_type == "newsItem" && linkType == "article" && defined(slug.current)]{"slug": slug.current}': OWNED_NEWS_SLUGS_QUERY_RESULT;
    '*[_id == "newsPage"][0].grid{\n  eyebrow,\n  headingLead,\n  headingStrong\n}': NEWS_GRID_HEADER_QUERY_RESULT;
    '*[_type == "practiceArea"] | order(orderRank){\n  _id,\n  title,\n  heroTitle,\n  lede,\n  cardSummary,\n  icon,\n  intro,\n  sections[]{ _key, heading, body },\n  faqs[]{ _key, question, answer },\n  "slug": slug.current,\n  "parentId": parent._ref\n}': ALL_QUERY_RESULT;
    "*[_id == $pageId][0].practiceAreas{\n  eyebrow,\n  headingLead,\n  headingStrong,\n  description,\n  cards[]{\n    _key,\n    icon,\n    title,\n    desc\n  }\n}": PRACTICE_AREAS_BAND_QUERY_RESULT;
    '*[\n  _type == "testimonial" && featured == true\n] | order(orderRank) [0...3]{\n  _id,\n  quote,\n  author,\n  tag\n}': FEATURED_TESTIMONIALS_QUERY_RESULT;
    '*[_type == "testimonial"] | order(orderRank){\n  _id,\n  quote,\n  author\n}': ALL_TESTIMONIALS_QUERY_RESULT;
    "*[_id == $pageId][0].testimonials{\n  eyebrow,\n  headingLead,\n  headingStrong\n}": TESTIMONIALS_BAND_QUERY_RESULT;
    '*[_id == "testimonialsPage"][0].testimonialsWall{\n  eyebrow,\n  headingLead,\n  headingStrong,\n  lede\n}': TESTIMONIALS_WALL_BAND_QUERY_RESULT;
    '*[_id == "trialExperiencePage"][0].trialResults.cases[]->{\n  _id,\n  name,\n  outcome,\n  note,\n  category,\n  categoryLabel\n}': TRIAL_RESULTS_QUERY_RESULT;
    '*[_type == "video"] | order(orderRank){\n  _id,\n  title,\n  wistiaId\n}': VIDEOS_QUERY_RESULT;
    '*[_id == "videosPage"][0].grid{\n  eyebrow,\n  headingLead,\n  headingStrong\n}': VIDEO_GRID_HEADER_QUERY_RESULT;
    "*[_id == $pageId][0].whyChoose{\n  eyebrow,\n  headingLead,\n  headingStrong,\n  features[]{\n    _key,\n    icon,\n    title,\n    body\n  }\n}": WHY_CHOOSE_BAND_QUERY_RESULT;
  }
}
