/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type AccentText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal";
  listItem?: never;
  markDefs?: null;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type TrialResultReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "trialResult";
};

export type TrialResultList = {
  _type: "trialResultList";
  cases: Array<
    {
      _key: string;
    } & TrialResultReference
  >;
};

export type EducationEntry = {
  _type: "educationEntry";
  school: string;
  location?: string;
  lines: Array<string>;
};

export type ConsultContent = {
  _type: "consultContent";
  eyebrow: string;
  headingLead: string;
  headingStrong: string;
  body: BlockContent;
  fineprint: string;
  thankYou: string;
};

export type CtaBarContent = {
  _type: "ctaBarContent";
  eyebrow: string;
  headingLead: string;
  headingRest: string;
  body: BlockContent;
  cta: CtaButton;
};

export type WhyChooseBand = {
  _type: "whyChooseBand";
  eyebrow: string;
  headingLead: string;
  headingStrong: string;
  features: Array<
    {
      _key: string;
    } & WhyChooseFeature
  >;
};

export type WhyChooseFeature = {
  _type: "whyChooseFeature";
  title: string;
  body: string;
  icon: "trophy" | "landmark" | "check" | "shield";
};

export type TestimonialsWallBand = {
  _type: "testimonialsWallBand";
  eyebrow: string;
  headingLead: string;
  headingStrong: string;
  lede: BlockContent;
};

export type TestimonialsBand = {
  _type: "testimonialsBand";
  eyebrow: string;
  headingLead: string;
  headingStrong: string;
};

export type AttorneysBand = {
  _type: "attorneysBand";
  eyebrow: string;
  headingLead: string;
  headingStrong: string;
  lede: BlockContent;
};

export type PracticeAreasBand = {
  _type: "practiceAreasBand";
  eyebrow: string;
  headingLead: string;
  headingStrong: string;
  description: BlockContent;
  cards: Array<
    {
      _key: string;
    } & PracticeAreaCard
  >;
};

export type PracticeAreaCard = {
  _type: "practiceAreaCard";
  title: string;
  desc: string;
  icon: "briefcase" | "users" | "layers" | "columns" | "search" | "doc";
};

export type SellingPoint = {
  _type: "sellingPoint";
  value: string;
  label: string;
};

export type CtaButton = {
  _type: "ctaButton";
  label: string;
  href: string;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  quote: string;
  author: string;
  tag?: string;
  featured?: boolean;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Attorney = {
  _id: string;
  _type: "attorney";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  name: string;
  slug: Slug;
  role: string;
  credential: string;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  photoAlt: string;
  phone: string;
  email?: string;
  practiceTags: Array<string>;
  bio?: BlockContent;
  education: Array<
    {
      _key: string;
    } & EducationEntry
  >;
  barAdmissions: Array<string>;
  honors: Array<string>;
  classesSeminars?: Array<string>;
  publishedWorks?: Array<string>;
  associations?: Array<string>;
  pastPositions?: Array<string>;
  representativeCases?: Array<string>;
  consult?: ConsultContent;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type TrialResult = {
  _id: string;
  _type: "trialResult";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  outcome: string;
  note: string;
  category: "landmark" | "federal" | "fraud";
  categoryLabel:
    | "Landmark Case"
    | "Federal Victory"
    | "White Collar"
    | "Health Care Fraud"
    | "Federal Fraud";
  teaser?: {
    title?: string;
    outcome?: string;
    note?: string;
  };
};

export type Consult = {
  _id: string;
  _type: "consult";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  content: ConsultContent;
};

export type CtaBar = {
  _id: string;
  _type: "ctaBar";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  content: CtaBarContent;
};

export type PracticeAreasPage = {
  _id: string;
  _type: "practiceAreasPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  consult?: ConsultContent;
};

export type NewsPage = {
  _id: string;
  _type: "newsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  consult?: ConsultContent;
};

export type VideosPage = {
  _id: string;
  _type: "videosPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  consult?: ConsultContent;
};

export type OurFirmPage = {
  _id: string;
  _type: "ourFirmPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  consult?: ConsultContent;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  consult?: ConsultContent;
};

export type AttorneysPage = {
  _id: string;
  _type: "attorneysPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  attorneys?: AttorneysBand;
  testimonials?: TestimonialsBand;
  whyChoose?: WhyChooseBand;
  consult?: ConsultContent;
};

export type TestimonialsPage = {
  _id: string;
  _type: "testimonialsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  testimonialsWall?: TestimonialsWallBand;
  practiceAreas?: PracticeAreasBand;
  ctaBar?: CtaBarContent;
  consult?: ConsultContent;
};

export type TrialExperiencePage = {
  _id: string;
  _type: "trialExperiencePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  trialResults?: TrialResultList;
  practiceAreas?: PracticeAreasBand;
  ctaBar?: CtaBarContent;
  consult?: ConsultContent;
};

export type VideoReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "video";
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    eyebrow: string;
    titleAccent: string;
    titleSecond: string;
    lead: BlockContent;
    ctas?: Array<
      {
        _key: string;
      } & CtaButton
    >;
    caption?: {
      name: string;
      role: string;
      watchLabel: string;
      video: VideoReference;
    };
  };
  sellingPoints?: {
    points: Array<
      {
        _key: string;
      } & SellingPoint
    >;
  };
  practiceAreas?: PracticeAreasBand;
  about?: {
    eyebrow: string;
    titleLead: string;
    titleStrong: string;
    body: BlockContent;
    resultsEyebrow: string;
    featured: Array<
      {
        _key: string;
      } & TrialResultReference
    >;
    quote: AccentText;
  };
  statement?: {
    eyebrow: string;
    headingItalic: string;
    headingBold: string;
    body: BlockContent;
    cta: CtaButton;
  };
  ctaBar?: CtaBarContent;
  attorneys?: AttorneysBand;
  firmStory?: {
    eyebrow: string;
    headingLead: string;
    headingStrong: string;
    body: BlockContent;
    cta: CtaButton;
  };
  testimonials?: TestimonialsBand;
  whyChoose?: WhyChooseBand;
  consult?: ConsultContent;
};

export type Video = {
  _id: string;
  _type: "video";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  wistiaId: string;
};

export type FirmDetails = {
  _id: string;
  _type: "firmDetails";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  phone: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | AccentText
  | BlockContent
  | TrialResultReference
  | TrialResultList
  | EducationEntry
  | ConsultContent
  | CtaBarContent
  | WhyChooseBand
  | WhyChooseFeature
  | TestimonialsWallBand
  | TestimonialsBand
  | AttorneysBand
  | PracticeAreasBand
  | PracticeAreaCard
  | SellingPoint
  | CtaButton
  | Testimonial
  | SanityImageAssetReference
  | Attorney
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | TrialResult
  | Consult
  | CtaBar
  | PracticeAreasPage
  | NewsPage
  | VideosPage
  | OurFirmPage
  | ContactPage
  | AttorneysPage
  | TestimonialsPage
  | TrialExperiencePage
  | VideoReference
  | HomePage
  | Video
  | FirmDetails
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/attorneys.ts
// Variable: ATTORNEY_CARDS_QUERY
// Query: *[_type == "attorney"] | order(orderRank){  _id,  name,  role,  credential,  photo,  photoAlt,  "slug": slug.current}
export type ATTORNEY_CARDS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  role: string;
  credential: string;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  photoAlt: string;
  slug: string;
}>;

// Source: src/sanity/lib/attorneys.ts
// Variable: ATTORNEY_SLUGS_QUERY
// Query: *[_type == "attorney" && defined(slug.current)]{"slug": slug.current}
export type ATTORNEY_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: src/sanity/lib/attorneys.ts
// Variable: ATTORNEY_QUERY
// Query: *[_type == "attorney" && slug.current == $slug][0]{  _id,  name,  role,  credential,  photo,  photoAlt,  phone,  email,  practiceTags,  bio,  education[]{    _key,    school,    location,    lines  },  barAdmissions,  honors,  classesSeminars,  publishedWorks,  associations,  pastPositions,  representativeCases,  "slug": slug.current}
export type ATTORNEY_QUERY_RESULT = {
  _id: string;
  name: string;
  role: string;
  credential: string;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  photoAlt: string;
  phone: string;
  email: string | null;
  practiceTags: Array<string>;
  bio: BlockContent | null;
  education: Array<{
    _key: string;
    school: string;
    location: string | null;
    lines: Array<string>;
  }>;
  barAdmissions: Array<string>;
  honors: Array<string>;
  classesSeminars: Array<string> | null;
  publishedWorks: Array<string> | null;
  associations: Array<string> | null;
  pastPositions: Array<string> | null;
  representativeCases: Array<string> | null;
  slug: string;
} | null;

// Source: src/sanity/lib/attorneys.ts
// Variable: ATTORNEYS_BAND_QUERY
// Query: *[_id == $pageId][0].attorneys{  eyebrow,  headingLead,  headingStrong,  lede}
export type ATTORNEYS_BAND_QUERY_RESULT = {
  eyebrow: string;
  headingLead: string;
  headingStrong: string;
  lede: BlockContent;
} | null;

// Source: src/sanity/lib/consult.ts
// Variable: CONSULT_QUERY
// Query: coalesce(  *[_id == $pageId][0].consult,  *[_id == "consult"][0].content){  eyebrow,  headingLead,  headingStrong,  body,  fineprint,  thankYou}
export type CONSULT_QUERY_RESULT =
  | {
      eyebrow: string;
      headingLead: string;
      headingStrong: null;
      body: BlockContent;
      fineprint: null;
      thankYou: null;
    }
  | {
      eyebrow: string;
      headingLead: string;
      headingStrong: string;
      body: BlockContent;
      fineprint: string;
      thankYou: string;
    }
  | null;

// Source: src/sanity/lib/ctaBar.ts
// Variable: CTA_BAR_QUERY
// Query: coalesce(  *[_id == $pageId][0].ctaBar,  *[_id == "ctaBar"][0].content){  eyebrow,  headingLead,  headingRest,  body,  cta{    label,    href  }}
export type CTA_BAR_QUERY_RESULT =
  | {
      eyebrow: string;
      headingLead: string;
      headingRest: null;
      body: BlockContent;
      cta: null;
    }
  | {
      eyebrow: string;
      headingLead: string;
      headingRest: string;
      body: BlockContent;
      cta: {
        label: string;
        href: string;
      };
    }
  | null;

// Source: src/sanity/lib/firmDetails.ts
// Variable: FIRM_DETAILS_QUERY
// Query: *[_id == "firmDetails"][0]{  title,  phone,  logo{    ...,    "dimensions": asset->metadata.dimensions  }}
export type FIRM_DETAILS_QUERY_RESULT =
  | {
      title: null;
      phone: null;
      logo: null;
    }
  | {
      title: string;
      phone: null;
      logo: null;
    }
  | {
      title: string | null;
      phone: null;
      logo: null;
    }
  | {
      title: null;
      phone: string;
      logo: null;
    }
  | {
      title: string;
      phone: string;
      logo: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        dimensions: SanityImageDimensions | null;
      } | null;
    }
  | null;

// Source: src/sanity/lib/homePage.ts
// Variable: HOME_HERO_QUERY
// Query: *[_id == "homePage"][0].hero{  eyebrow,  titleAccent,  titleSecond,  lead,  ctas[]{    _key,    label,    href  },  caption{    name,    role,    watchLabel,    video->{      wistiaId    }  }}
export type HOME_HERO_QUERY_RESULT = null | {
  eyebrow: string;
  titleAccent: string;
  titleSecond: string;
  lead: BlockContent;
  ctas: Array<{
    _key: string;
    label: string;
    href: string;
  }> | null;
  caption: {
    name: string;
    role: string;
    watchLabel: string;
    video: {
      wistiaId: string;
    };
  } | null;
};

// Source: src/sanity/lib/homePage.ts
// Variable: HOME_SELLING_POINTS_QUERY
// Query: *[_id == "homePage"][0].sellingPoints.points[]{  _key,  value,  label}
export type HOME_SELLING_POINTS_QUERY_RESULT = Array<{
  _key: string;
  value: string;
  label: string;
}> | null;

// Source: src/sanity/lib/homePage.ts
// Variable: HOME_ABOUT_QUERY
// Query: *[_id == "homePage"][0].about{  eyebrow,  titleLead,  titleStrong,  body,  resultsEyebrow,  quote,  featured[]->{    _id,    "outcome": coalesce(teaser.outcome, outcome),    "caseName": coalesce(teaser.title, name),    "note": coalesce(teaser.note, note)  }}
export type HOME_ABOUT_QUERY_RESULT = null | {
  eyebrow: string;
  titleLead: string;
  titleStrong: string;
  body: BlockContent;
  resultsEyebrow: string;
  quote: AccentText;
  featured: Array<{
    _id: string;
    outcome: string;
    caseName: string;
    note: string;
  }>;
};

// Source: src/sanity/lib/homePage.ts
// Variable: HOME_STATEMENT_QUERY
// Query: *[_id == "homePage"][0].statement{  eyebrow,  headingItalic,  headingBold,  body,  cta{    label,    href  }}
export type HOME_STATEMENT_QUERY_RESULT = null | {
  eyebrow: string;
  headingItalic: string;
  headingBold: string;
  body: BlockContent;
  cta: {
    label: string;
    href: string;
  };
};

// Source: src/sanity/lib/homePage.ts
// Variable: HOME_FIRM_STORY_QUERY
// Query: *[_id == "homePage"][0].firmStory{  eyebrow,  headingLead,  headingStrong,  body,  cta{    label,    href  }}
export type HOME_FIRM_STORY_QUERY_RESULT = null | {
  eyebrow: string;
  headingLead: string;
  headingStrong: string;
  body: BlockContent;
  cta: {
    label: string;
    href: string;
  };
};

// Source: src/sanity/lib/practiceAreasBand.ts
// Variable: PRACTICE_AREAS_BAND_QUERY
// Query: *[_id == $pageId][0].practiceAreas{  eyebrow,  headingLead,  headingStrong,  description,  cards[]{    _key,    icon,    title,    desc  }}
export type PRACTICE_AREAS_BAND_QUERY_RESULT = {
  eyebrow: string;
  headingLead: string;
  headingStrong: string;
  description: BlockContent;
  cards: Array<{
    _key: string;
    icon: "briefcase" | "columns" | "doc" | "layers" | "search" | "users";
    title: string;
    desc: string;
  }>;
} | null;

// Source: src/sanity/lib/testimonials.ts
// Variable: FEATURED_TESTIMONIALS_QUERY
// Query: *[  _type == "testimonial" && featured == true] | order(orderRank) [0...3]{  _id,  quote,  author,  tag}
export type FEATURED_TESTIMONIALS_QUERY_RESULT = Array<{
  _id: string;
  quote: string;
  author: string;
  tag: string | null;
}>;

// Source: src/sanity/lib/testimonials.ts
// Variable: ALL_TESTIMONIALS_QUERY
// Query: *[_type == "testimonial"] | order(orderRank){  _id,  quote,  author}
export type ALL_TESTIMONIALS_QUERY_RESULT = Array<{
  _id: string;
  quote: string;
  author: string;
}>;

// Source: src/sanity/lib/testimonials.ts
// Variable: TESTIMONIALS_BAND_QUERY
// Query: *[_id == $pageId][0].testimonials{  eyebrow,  headingLead,  headingStrong}
export type TESTIMONIALS_BAND_QUERY_RESULT = {
  eyebrow: string;
  headingLead: string;
  headingStrong: string;
} | null;

// Source: src/sanity/lib/testimonials.ts
// Variable: TESTIMONIALS_WALL_BAND_QUERY
// Query: *[_id == "testimonialsPage"][0].testimonialsWall{  eyebrow,  headingLead,  headingStrong,  lede}
export type TESTIMONIALS_WALL_BAND_QUERY_RESULT = {
  eyebrow: string;
  headingLead: string;
  headingStrong: string;
  lede: BlockContent;
} | null;

// Source: src/sanity/lib/trialResults.ts
// Variable: TRIAL_RESULTS_QUERY
// Query: *[_id == "trialExperiencePage"][0].trialResults.cases[]->{  _id,  name,  outcome,  note,  category,  categoryLabel}
export type TRIAL_RESULTS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  outcome: string;
  note: string;
  category: "federal" | "fraud" | "landmark";
  categoryLabel:
    | "Federal Fraud"
    | "Federal Victory"
    | "Health Care Fraud"
    | "Landmark Case"
    | "White Collar";
}> | null;

// Source: src/sanity/lib/whyChoose.ts
// Variable: WHY_CHOOSE_BAND_QUERY
// Query: *[_id == $pageId][0].whyChoose{  eyebrow,  headingLead,  headingStrong,  features[]{    _key,    icon,    title,    body  }}
export type WHY_CHOOSE_BAND_QUERY_RESULT = {
  eyebrow: string;
  headingLead: string;
  headingStrong: string;
  features: Array<{
    _key: string;
    icon: "check" | "landmark" | "shield" | "trophy";
    title: string;
    body: string;
  }>;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "attorney"] | order(orderRank){\n  _id,\n  name,\n  role,\n  credential,\n  photo,\n  photoAlt,\n  "slug": slug.current\n}': ATTORNEY_CARDS_QUERY_RESULT;
    '*[_type == "attorney" && defined(slug.current)]{"slug": slug.current}': ATTORNEY_SLUGS_QUERY_RESULT;
    '*[_type == "attorney" && slug.current == $slug][0]{\n  _id,\n  name,\n  role,\n  credential,\n  photo,\n  photoAlt,\n  phone,\n  email,\n  practiceTags,\n  bio,\n  education[]{\n    _key,\n    school,\n    location,\n    lines\n  },\n  barAdmissions,\n  honors,\n  classesSeminars,\n  publishedWorks,\n  associations,\n  pastPositions,\n  representativeCases,\n  "slug": slug.current\n}': ATTORNEY_QUERY_RESULT;
    "*[_id == $pageId][0].attorneys{\n  eyebrow,\n  headingLead,\n  headingStrong,\n  lede\n}": ATTORNEYS_BAND_QUERY_RESULT;
    'coalesce(\n  *[_id == $pageId][0].consult,\n  *[_id == "consult"][0].content\n){\n  eyebrow,\n  headingLead,\n  headingStrong,\n  body,\n  fineprint,\n  thankYou\n}': CONSULT_QUERY_RESULT;
    'coalesce(\n  *[_id == $pageId][0].ctaBar,\n  *[_id == "ctaBar"][0].content\n){\n  eyebrow,\n  headingLead,\n  headingRest,\n  body,\n  cta{\n    label,\n    href\n  }\n}': CTA_BAR_QUERY_RESULT;
    '*[_id == "firmDetails"][0]{\n  title,\n  phone,\n  logo{\n    ...,\n    "dimensions": asset->metadata.dimensions\n  }\n}': FIRM_DETAILS_QUERY_RESULT;
    '*[_id == "homePage"][0].hero{\n  eyebrow,\n  titleAccent,\n  titleSecond,\n  lead,\n  ctas[]{\n    _key,\n    label,\n    href\n  },\n  caption{\n    name,\n    role,\n    watchLabel,\n    video->{\n      wistiaId\n    }\n  }\n}': HOME_HERO_QUERY_RESULT;
    '*[_id == "homePage"][0].sellingPoints.points[]{\n  _key,\n  value,\n  label\n}': HOME_SELLING_POINTS_QUERY_RESULT;
    '*[_id == "homePage"][0].about{\n  eyebrow,\n  titleLead,\n  titleStrong,\n  body,\n  resultsEyebrow,\n  quote,\n  featured[]->{\n    _id,\n    "outcome": coalesce(teaser.outcome, outcome),\n    "caseName": coalesce(teaser.title, name),\n    "note": coalesce(teaser.note, note)\n  }\n}': HOME_ABOUT_QUERY_RESULT;
    '*[_id == "homePage"][0].statement{\n  eyebrow,\n  headingItalic,\n  headingBold,\n  body,\n  cta{\n    label,\n    href\n  }\n}': HOME_STATEMENT_QUERY_RESULT;
    '*[_id == "homePage"][0].firmStory{\n  eyebrow,\n  headingLead,\n  headingStrong,\n  body,\n  cta{\n    label,\n    href\n  }\n}': HOME_FIRM_STORY_QUERY_RESULT;
    "*[_id == $pageId][0].practiceAreas{\n  eyebrow,\n  headingLead,\n  headingStrong,\n  description,\n  cards[]{\n    _key,\n    icon,\n    title,\n    desc\n  }\n}": PRACTICE_AREAS_BAND_QUERY_RESULT;
    '*[\n  _type == "testimonial" && featured == true\n] | order(orderRank) [0...3]{\n  _id,\n  quote,\n  author,\n  tag\n}': FEATURED_TESTIMONIALS_QUERY_RESULT;
    '*[_type == "testimonial"] | order(orderRank){\n  _id,\n  quote,\n  author\n}': ALL_TESTIMONIALS_QUERY_RESULT;
    "*[_id == $pageId][0].testimonials{\n  eyebrow,\n  headingLead,\n  headingStrong\n}": TESTIMONIALS_BAND_QUERY_RESULT;
    '*[_id == "testimonialsPage"][0].testimonialsWall{\n  eyebrow,\n  headingLead,\n  headingStrong,\n  lede\n}': TESTIMONIALS_WALL_BAND_QUERY_RESULT;
    '*[_id == "trialExperiencePage"][0].trialResults.cases[]->{\n  _id,\n  name,\n  outcome,\n  note,\n  category,\n  categoryLabel\n}': TRIAL_RESULTS_QUERY_RESULT;
    "*[_id == $pageId][0].whyChoose{\n  eyebrow,\n  headingLead,\n  headingStrong,\n  features[]{\n    _key,\n    icon,\n    title,\n    body\n  }\n}": WHY_CHOOSE_BAND_QUERY_RESULT;
  }
}
